name: Project go-cli

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
        paths-ignore:
            - '**.md'

jobs:
    build:
        runs-on: ubuntu-20.04
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version-file: go.mod
            - name: Install dependencies
              run: go mod tidy

            - name: Build
              run: go build -v ./...

        